module.exports = grammar({
  name: "javascript",
  rules: {
    program: ..., // rule omitted for brevity
    hash_bang_line: ..., // rule omitted for brevity
    export_statement: ..., // rule omitted for brevity
    namespace_export: ..., // rule omitted for brevity
    export_clause: ..., // rule omitted for brevity
    export_specifier: ..., // rule omitted for brevity
    _module_export_name: ..., // rule omitted for brevity
    declaration: ..., // rule omitted for brevity
    import: ..., // rule omitted for brevity
    import_statement: ..., // rule omitted for brevity
    import_clause: ..., // rule omitted for brevity
    _from_clause: ..., // rule omitted for brevity
    namespace_import: ..., // rule omitted for brevity
    named_imports: ..., // rule omitted for brevity
    import_specifier: ..., // rule omitted for brevity
    import_attribute: ..., // rule omitted for brevity
    statement: ..., // rule omitted for brevity
    expression_statement: ..., // rule omitted for brevity
    variable_declaration: ..., // rule omitted for brevity
    lexical_declaration: ..., // rule omitted for brevity
    variable_declarator: ..., // rule omitted for brevity
    statement_block: ..., // rule omitted for brevity
    else_clause: ..., // rule omitted for brevity
    if_statement: ..., // rule omitted for brevity
    switch_statement: ..., // rule omitted for brevity
    for_statement: ..., // rule omitted for brevity
    for_in_statement: ..., // rule omitted for brevity
    _for_header: ..., // rule omitted for brevity
    while_statement: ..., // rule omitted for brevity
    do_statement: ..., // rule omitted for brevity
    try_statement: ..., // rule omitted for brevity
    with_statement: ..., // rule omitted for brevity
    break_statement: ..., // rule omitted for brevity
    continue_statement: ..., // rule omitted for brevity
    debugger_statement: ..., // rule omitted for brevity
    return_statement: ..., // rule omitted for brevity
    throw_statement: ..., // rule omitted for brevity
    empty_statement: ..., // rule omitted for brevity
    labeled_statement: ..., // rule omitted for brevity
    switch_body: ..., // rule omitted for brevity
    switch_case: ..., // rule omitted for brevity
    switch_default: ..., // rule omitted for brevity
    catch_clause: ..., // rule omitted for brevity
    finally_clause: ..., // rule omitted for brevity
    parenthesized_expression: ..., // rule omitted for brevity
    _expressions: ..., // rule omitted for brevity
    expression: ..., // rule omitted for brevity
    primary_expression: ..., // rule omitted for brevity
    yield_expression: ..., // rule omitted for brevity
    object: ..., // rule omitted for brevity
    object_pattern: ..., // rule omitted for brevity
    assignment_pattern: ..., // rule omitted for brevity
    object_assignment_pattern: ..., // rule omitted for brevity
    array: ..., // rule omitted for brevity
    array_pattern: ..., // rule omitted for brevity
    _jsx_element: ..., // rule omitted for brevity
    jsx_element: ..., // rule omitted for brevity
    html_character_reference: ..., // rule omitted for brevity
    jsx_expression: ..., // rule omitted for brevity
    _jsx_child: ..., // rule omitted for brevity
    jsx_opening_element: ..., // rule omitted for brevity
    jsx_identifier: ..., // rule omitted for brevity
    _jsx_identifier: ..., // rule omitted for brevity
    nested_identifier: ..., // rule omitted for brevity
    jsx_namespace_name: ..., // rule omitted for brevity
    _jsx_element_name: ..., // rule omitted for brevity
    jsx_closing_element: ..., // rule omitted for brevity
    jsx_self_closing_element: ..., // rule omitted for brevity
    _jsx_attribute: ..., // rule omitted for brevity
    _jsx_attribute_name: ..., // rule omitted for brevity
    jsx_attribute: ..., // rule omitted for brevity
    _jsx_string: ..., // rule omitted for brevity
    unescaped_double_jsx_string_fragment: ..., // rule omitted for brevity
    unescaped_single_jsx_string_fragment: ..., // rule omitted for brevity
    _jsx_attribute_value: ..., // rule omitted for brevity
    class: ..., // rule omitted for brevity
    class_declaration: ..., // rule omitted for brevity
    class_heritage: ..., // rule omitted for brevity
    function_expression: ..., // rule omitted for brevity
    function_declaration: ..., // rule omitted for brevity
    generator_function: ..., // rule omitted for brevity
    generator_function_declaration: ..., // rule omitted for brevity
    arrow_function: ..., // rule omitted for brevity
    _call_signature: ..., // rule omitted for brevity
    _formal_parameter: ..., // rule omitted for brevity
    optional_chain: ..., // rule omitted for brevity
    call_expression: ..., // rule omitted for brevity
    new_expression: ..., // rule omitted for brevity
    await_expression: ..., // rule omitted for brevity
    member_expression: ..., // rule omitted for brevity
    subscript_expression: ..., // rule omitted for brevity
    _lhs_expression: ..., // rule omitted for brevity
    assignment_expression: ..., // rule omitted for brevity
    _augmented_assignment_lhs: ..., // rule omitted for brevity
    augmented_assignment_expression: ..., // rule omitted for brevity
    _initializer: ..., // rule omitted for brevity
    _destructuring_pattern: ..., // rule omitted for brevity
    spread_element: ..., // rule omitted for brevity
    ternary_expression: ..., // rule omitted for brevity
    binary_expression: ..., // rule omitted for brevity
    unary_expression: ..., // rule omitted for brevity
    update_expression: ..., // rule omitted for brevity
    sequence_expression: ..., // rule omitted for brevity
    string: ..., // rule omitted for brevity
    unescaped_double_string_fragment: ..., // rule omitted for brevity
    unescaped_single_string_fragment: ..., // rule omitted for brevity
    escape_sequence: ..., // rule omitted for brevity
    comment: ..., // rule omitted for brevity
    template_string: ..., // rule omitted for brevity
    template_substitution: ..., // rule omitted for brevity
    regex: ..., // rule omitted for brevity
    regex_pattern: ..., // rule omitted for brevity
    regex_flags: ..., // rule omitted for brevity
    number: ..., // rule omitted for brevity
    _identifier: ..., // rule omitted for brevity
    identifier: ..., // rule omitted for brevity
    private_property_identifier: ..., // rule omitted for brevity
    meta_property: ..., // rule omitted for brevity
    this: ..., // rule omitted for brevity
    super: ..., // rule omitted for brevity
    true: ..., // rule omitted for brevity
    false: ..., // rule omitted for brevity
    null: ..., // rule omitted for brevity
    undefined: ..., // rule omitted for brevity
    arguments: ..., // rule omitted for brevity
    decorator: ..., // rule omitted for brevity
    decorator_member_expression: ..., // rule omitted for brevity
    decorator_call_expression: ..., // rule omitted for brevity
    class_body: ..., // rule omitted for brevity
    field_definition: ..., // rule omitted for brevity
    formal_parameters: ..., // rule omitted for brevity
    class_static_block: ..., // rule omitted for brevity
    pattern: ..., // rule omitted for brevity
    rest_pattern: ..., // rule omitted for brevity
    method_definition: ..., // rule omitted for brevity
    pair: ..., // rule omitted for brevity
    pair_pattern: ..., // rule omitted for brevity
    _property_name: ..., // rule omitted for brevity
    computed_property_name: ..., // rule omitted for brevity
    _reserved_identifier: ..., // rule omitted for brevity
    _semicolon: ..., // rule omitted for brevity
  },
  extras: ["$.comment", "$.html_comment", "/[\s\p{Zs}\uFEFF\u2028\u2029\u2060\u200B]/"],
  conflicts: [["$.primary_expression", "$._property_name"], ["$.primary_expression", "$._property_name", "$.arrow_function"], ["$.primary_expression", "$.arrow_function"], ["$.primary_expression", "$.method_definition"], ["$.primary_expression", "$.rest_pattern"], ["$.primary_expression", "$.pattern"], ["$.primary_expression", "$._for_header"], ["$.variable_declarator", "$._for_header"], ["$.array", "$.array_pattern"], ["$.object", "$.object_pattern"], ["$.assignment_expression", "$.pattern"], ["$.assignment_expression", "$.object_assignment_pattern"], ["$.labeled_statement", "$._property_name"], ["$.computed_property_name", "$.array"], ["$.binary_expression", "$._initializer"], ["$.class_static_block", "$._property_name"]],
  inline: ["$._call_signature", "$._formal_parameter", "$._expressions", "$._semicolon", "$._identifier", "$._reserved_identifier", "$._jsx_attribute", "$._jsx_element_name", "$._jsx_child", "$._jsx_element", "$._jsx_attribute_name", "$._jsx_attribute_value", "$._jsx_identifier", "$._lhs_expression"],
  externals: ["$._automatic_semicolon", "$._template_chars", "$._ternary_qmark", "$.html_comment", "||", "$.escape_sequence", "$.regex_pattern", "$.jsx_text"],
  word: "identifier",
  supertypes: ["$.statement", "$.declaration", "$.expression", "$.primary_expression", "$.pattern"],
})